NaukaFiszek/Controllers/FiszkaController.cs
//#define ToTest
using DTO;
using DTO.Enums;
using NaukaFiszek.Filter;
using DTO.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NaukaFiszek.Controllers
{
    public class FiszkaController : Controller
    {
#if !ToTest
        [FiszkiAutorize(IsAjaxRequest = true)]
#endif
        public ActionResult Dodaj(
#if !ToTest
            int idFicheSet
#endif
            )
        {
            return View(new Fiche()
            {
#if !ToTest
                IdFicheSet = idFicheSet,
#endif
                FicheResponses = new FicheResponse[]
                {
#if ToTest
                    new FicheResponse(){Id=1,Name="ble",IsCorect=true},
                    new FicheResponse(){Id=2,Name="ble ble"}
#endif
                }
            }
            );
        }
        public ActionResult Edit(int id)
        {
            using (Conector.Fiche ficheConector = new Conector.Fiche())
            {
                var fiche = ficheConector.LoadFiche(id);
                return View("Dodaj", fiche);
            }
        }
        [HttpPost]
        public void DeleteResponse(IdPost fiche)
        {
            using (Conector.Fiche ficheConector = new Conector.Fiche())
            {
                ficheConector.DeleteResponse(fiche.id);
            }
        }

        [HttpPost]
        public void Delete(IdPost fiche)
        {
            using (Conector.Fiche ficheConector = new Conector.Fiche())
            {
                ficheConector.DeleteFiche(fiche.id);
            }
        }
        [HttpPost]
        public void Dodaj(Fiche fiche)
        {
            using (Conector.Fiche ficheConector = new Conector.Fiche())
            {
                ficheConector.SendFiche(fiche);
            }
        }
        [HttpGet]
        public ActionResult ResponseEditorWithData(int? idFicheSet)
        {
            return View(new FicheResponse()
            {
                Id = idFicheSet ?? 0
            });
        }
        [HttpGet]
        public ActionResult ResponseRow()
        {
            return View(new FicheResponse());
        }
        [HttpGet]
        public ActionResult ResponseRowWithData(FicheResponse fiche)
        {
            return View("ResponseRow", fiche);
        }
    }
}

NaukaFiszek/Controllers/ZestawController.cs
using Conector;
using NaukaFiszek.Filter;
using NaukaFiszek.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NaukaFiszek.Controllers
{
    public class ZestawController : Controller
    {
        [FiszkiAutorize(IsAjaxRequest = true)]
        public ActionResult DodajZestaw()
        {
            return PartialView();
        }
        [FiszkiAutorize(IsAjaxRequest = true)]
        [HttpPost]
        public ActionResult DodajZestaw(string nameSet)
        {
            using (SetFiche setFiche = new SetFiche())
            {
                return Json(new DTO.Models.IdPost(setFiche.AddSetFiche(nameSet, UserFiche.CurentUser.Id)));
            }
        }
        [FiszkiAutorize(IsAjaxRequest = true)]
        public ActionResult ListaZestawów()
        {
            using (SetFiche setFiszka = new SetFiche())
            {
                return View(setFiszka.SearchSetsFiche(UserFiche.CurentUser.Id, null));
            }
        }
        [FiszkiAutorize(IsAjaxRequest = true)]
        [HttpPost]
        public void Delete(int id)
        {
            using (SetFiche setFiche = new SetFiche())
            {
                setFiche.Remove(id);
            }
        }

        [HttpGet]
        [FiszkiAutorize(IsAjaxRequest = true)]
        public ActionResult Edytuj(int id)
        {
            DTO.Models.SetFicheDetails setFicheDetails = new DTO.Models.SetFicheDetails();
            using (Fiche fiche = new Fiche())
            {
                setFicheDetails.Fiches = fiche.SearchFiches(id);
            }
            using (SetFiche setFiche = new SetFiche())
            {
                var fiche = setFiche.SearchSetsFiche(UserFiche.CurentUser.Id, id).First();
                setFicheDetails.Name = fiche.Name;
            }
            setFicheDetails.IdSetFiche = id;
            return View(setFicheDetails);
        }

    }
}

NaukaFiszek/Views/Zestaw/DodajZestaw.cshtml
@{
    Layout = null;
}
<h4>Dodawanie zestawu</h4>
<br />
<label for="NameSet">Nazwa zestawu</label>
<input type="text" id="NameSet" />
<button id="AddNewSet">Dodaj zestaw</button>
<script type="text/javascript">
    $('#AddNewSet').click(function (e) {
        var data = {
            nameSet: $('#NameSet').val()
        };
        if (ValidatingControlMinLenght2ById('NameSet')) {

            PostAction('@Url.Action("DodajZestaw","Zestaw")', data, function (dataResponse) {
                loadPageUsingUrl(e, 'Zestaw/Edytuj/' + dataResponse.id);
        });
        }
    });
</script>

NaukaFiszek/Views/Zestaw/Edytuj.cshtml
@{
    Layout = null;
}
@model DTO.Models.SetFicheDetails
<h4>Edytowanie zestawu</h4>
<br />
<p>
    @Html.ActionLink("Dodaj Fiszke", "Dodaj", "Fiszka", new { idFicheSet = Model.IdSetFiche }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fiches.First().Prompt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fiches.First().Response)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Fiches)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Prompt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Response)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", "Fiszka", new { id = item.Id }, null)
                @Html.ActionLink("Usuń", "Delete", null, new { @class = "RemoveFiche", id = item.Id })
            </td>
        </tr>
    }
    @Html.HiddenFor(model => model.IdSetFiche)

</table>
<script src="~/Scripts/Zestaw/Edytuj.js"></script>

NaukaFiszek/Views/Zestaw/ListaZestawów.cshtml
@{
    Layout = null;
}
@using  DTO.Enums
@model IEnumerable<DTO.Models.SetFiche>
<h4>Przeglądanie zestawów</h4>
<br />
<p>
    <a href=@Url.Action("DodajZestaw","Zestaw") id="addSet">Dodaj zestaw</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="SetElement" id=@item.Id>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td class="">
                @Html.ActionLink("Edytuj", "Edytuj", null, new { id = item.Id, @class = "EditSet" }) 
                @Html.ActionLink("Usuń", "Delete", null, new { id = item.Id, @class = "Remover" })
            </td>
        </tr>
    }

</table>

<script src="~/Scripts/Zestaw/ListaZestawów.js"></script>