NaukaFiszek/Controllers/ComonController.cs
using DTO.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
namespace NaukaFiszek.Controllers
{
    public class ComonController : Controller
    {
        static bool IsLoaded = false;

        void LoadFolder()
        {
            if (!IsLoaded)
            {
                DirectoryInfo directoryInfo = new DirectoryInfo(Server.MapPath(ConfigurationManager.AppSettings["pathfile"]));
                if (!directoryInfo.Exists)
                {
                    directoryInfo.Create();
                }
                IsLoaded = true;
            }
        }
        // GET: Comon
        public ActionResult Index()
        {
            return View();
        }
        public string PathContent
        {
            get
            {
                LoadFolder();
                return Server.MapPath(ConfigurationManager.AppSettings["pathfile"]);
            }
        }
        [HttpPost]
        public JsonResult SaveFile()
        {

            HttpPostedFileBase file = Request.Files[0];
            int FileId;
            using (Conector.Comon common = new Conector.Comon())
            {
                FileId = common.SaveFile(Path.GetExtension(file.FileName));

                MemoryStream target = new MemoryStream();
                file.InputStream.CopyTo(target);
                byte[] data = target.ToArray();

                global::System.IO.File.WriteAllBytes(Path.Combine(PathContent, FileId.ToString()), data);
            }
            return Json(new SaveFileResponse() { Id = FileId });
        }



        public ActionResult LoadFile(int id)
        {
            string extension = null;
            using (Conector.Comon common = new Conector.Comon())
            {
                extension = common.GetExtension(id);
            }
            return File(global::System.IO.File.ReadAllBytes(Path.Combine(PathContent, id.ToString())), extension);
        }
        public ActionResult DontFindSet()
        {
            return View(nameof(DontFindSet));
        }

    }
}

NaukaFiszek/Controllers/GraController.cs
using NaukaFiszek.Filter;
using DTO.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NaukaFiszek.Logic;
using DTO.Enums;

namespace NaukaFiszek.Controllers
{
    public class GraController : Controller
    {
        [HttpGet]
        public ActionResult Prompt(Fiche fiche)
        {
            return View(fiche);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">numer zestawu uczącego</param>
        /// <returns></returns>
        [FiszkiAutorize(IsAjaxRequest = true)]
        [HttpGet]
        public ActionResult NextFicheTeach(int id)
        {
            using (Conector.Game conector = new Conector.Game())
            {
                var randFiche = conector.NextFiche(id);
                if (randFiche.IdFiche != -1)
                {
                    GameState game = new GameState();
                    using (Conector.Fiche ficheConector = new Conector.Fiche())
                    {
                        game.Fiche = ficheConector.LoadFiche(randFiche.IdFiche);
                        game.IdTeachSet = id;
                        game.TypeAnswer = randFiche.TypeAnswer;
                        game.LimitTimeSek = randFiche.LimitTimeSek;
                        if (!game.TypeAnswer.Can(game.Fiche))
                        {
                            return UserChose(game);
                        }
                        return (game.TypeAnswer) switch
                        {

                            DTO.Enums.TypeAnswer.WriteTextUserChose => WriteText(game),
                            DTO.Enums.TypeAnswer.WriteText => WriteText(game),
                            DTO.Enums.TypeAnswer.UserChose => UserChose(game),
                            DTO.Enums.TypeAnswer.ChoseOption => ChoseOption(game),
                            DTO.Enums.TypeAnswer.Hangman => Hangman(game),
                            _ => null
                        };
                    }
                }
                else
                {
                    return GameEnd();
                }

            }
        }
        [HttpGet]
        public ActionResult Hangman(GameState game)
        {
            HangmanGameState hangmanGame = new HangmanGameState(game);
            return View(nameof(Hangman), new HangmanGameState(hangmanGame));
        }

        [HttpGet]
        public ActionResult UserChose(GameState game)
        {
            return View(nameof(UserChose), game);
        }
        [HttpGet]
        public ActionResult WriteText(GameState game)
        {
            return View(nameof(WriteText), game);
        }
        [HttpGet]
        public ActionResult ChoseOption(GameState game)
        {
            return View(nameof(ChoseOption), game);
        }

        [HttpGet]
        public ActionResult GameEnd(bool isMulti = false)
        {
            return View(nameof(GameEnd), isMulti);
        }
        [FiszkiAutorize(IsAjaxRequest = true)]
        [HttpPost]
        public void SendAnswer(SendAnswerRequest request)
        {
            using (Conector.Game conector = new Conector.Game())
            {
                conector.SendAnswer(request.idTeachSet, request.IdFiche, request.IsCorrect);
            }
        }
        public ActionResult Common()
        {
            return View();
        }
    }
}

NaukaFiszek/Controllers/NaukaZestawController.cs
//#define ToTest
using DTO;
using NaukaFiszek.Filter;
using NaukaFiszek.Logic;
using DTO.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NaukaFiszek.Controllers
{
    public class NaukaZestawController : Controller
    {
        public NaukaZestawController()
        {
#if ToTest
            if (UserFiche.CurentUser == null)
            {
                UserFiche.CurentUser = new UserFiche() { Id = 5 };
            }
#endif
        }
#if !ToTest
        [FiszkiAutorize(IsAjaxRequest = true)]
#endif
        [HttpGet]
        public ActionResult Add(int? id)
        {

            TeachSetFiche teachSetFiche = new TeachSetFiche();
            if (id == null)
            {
                using (Conector.SetFiche setFicheConector = new Conector.SetFiche())
                {
                    teachSetFiche.AvailableSetFiches = setFicheConector.SearchSetsFiche(UserFiche.CurentUser.Id, null);
                }
            }
            else
            {
                teachSetFiche.IdSetFiche = id.Value;
            }
            teachSetFiche.teachBags = new List<TeachBag>();
            return View(teachSetFiche);
        }

#if !ToTest
        [FiszkiAutorize(IsAjaxRequest = true)]
#endif
        [HttpPost]
        public ActionResult Add(TeachSetFiche fiche)
        {
            using (Conector.TeachSetFiche conector = new Conector.TeachSetFiche())
            {
                conector.Add(fiche);
            }
            return Json(new IdPost(fiche.IdSetFiche));
        }
        [HttpPost]
        public void Delete(int id)
        {
            using (Conector.TeachSetFiche conector = new Conector.TeachSetFiche())
            {
                conector.Delete(id);
            }
        }
        [FiszkiAutorize(IsAjaxRequest = true)]
        public ActionResult List()
        {

            using (Conector.SetFiche conector = new Conector.SetFiche())
            {
                if (!conector.AnySetsFicheExist(UserFiche.CurentUser.Id))
                {
                    return RedirectToAction(nameof(ComonController.DontFindSet), "Comon");
                }
            }
            using (Conector.TeachSetFiche conector = new Conector.TeachSetFiche())
            {
                return View(conector.SearchTeachSetsByUser(UserFiche.CurentUser.Id));
            }
        }
        public ActionResult BagRow()
        {
            return View();
        }
        public ActionResult BagEditor()
        {
            return View();
        }

    }
}

NaukaFiszek/Views/Gra/ChoseOption.cshtml
@model DTO.Models.GameState
@{
    Layout = null;
}
<style>
    .WrongResponse {
        color: red;
    }

    .CorrectResponse {
        color: green;
    }
</style>
<div class="form-horizontal">
    <h4>Wybierz poprawne odpowiedzi</h4>
    <hr />
    @Html.Partial("~/Views/Gra/Prompt.cshtml", Model.Fiche)
    @foreach (var item in Model.Fiche.FicheResponses)
    {
        string urlFile = Url.Action("LoadFile", "Comon", new { id = item.IdFile });
        string idChexbox = "ResponseCheckbox" + item.Id;
        <div class="form-group">
            <div class="bottom ResponseDiv gameDiv">
                <input class="AnswerCheckbox" type="checkbox" id=@idChexbox name="checkbox" />
                <label class="AnswerLabel" for=@idChexbox>@item.Name</label>
                <br />
                @if (item.TypePrompt == DTO.Enums.ContentType.Sound)
                {
                    <audio controls="controls">
                        <source src=@urlFile />
                    </audio>
                }
                @if (item.TypePrompt == DTO.Enums.ContentType.Image)
                {
                    <img src=@urlFile />
                }
                @if (item.TypePrompt == DTO.Enums.ContentType.Movie)
                {
                    <video controls="controls">
                        <source src=@urlFile />
                    </video>
                }
                <input type="hidden" class="CorrectMark" value=@(item.IsCorect?"1":"0" ) />
            </div>
        </div>
        <br />
    }
</div>
@Html.Partial("~/Views/Gra/Common.cshtml")
<script src="~/Scripts/Game/ChoseOption.js"></script>

NaukaFiszek/Views/Gra/Common.cshtml
@model DTO.Models.GameState
@{
    Layout = null;
}
<style type="text/css">
    .CorrectResponse {
        color: green;
    }

    .WrongResponse {
        color: red;
    }

    #TimeText {
        color: red;
    }
</style>
<div class="form-group">

    <button id="AdmitAnswer" class="form-control">Sprawdź</button>

</div>

<div class="form-group" hidden="hidden" id="CorrectAnswerDiv">

    <h3 id="CorrectAnswerLabel">Poprawna odpowiedź to : </h3>
    <h3 id="CorrectAnswerText">@Model.Fiche.Response</h3>
</div>

<div class="form-group">
    <div hidden="hidden" id="UserChoseDiv">
        <button id="Know" class="form-control">Wiem</button>
        <button id="NotKnow" class="form-control">Nie wiem</button>
    </div>
</div>
@if (!Model.IsMultiPlayer)
{
    <div class="form-group">
        <a href=@Url.Action("NextFicheTeach", "Gra", new { id = Model.IdTeachSet }) id="NextFiche" hidden="hidden">Następna fiszka</a>

    </div>
}
<span id="TimeText"></span>
@Html.HiddenFor(model => model.LimitTimeSek)
@Html.HiddenFor(model => model.IsMultiPlayer)
@Html.HiddenFor(model => model.IdTeachSet)
@Html.HiddenFor(model => model.Fiche.Id)
@Html.HiddenFor(model => model.IntTypeAnswer, new { id = "TypeAnswer" })
<script src="~/Scripts/Game/Common.js"></script>

NaukaFiszek/Views/Gra/GameEnd.cshtml
@model bool
@{
    Layout = null;
}
<h4>Super, już umiesz</h4>
<br />
@if(Model)
{

}
else
{
<span>Na ten moment nie ma więcej fiszek do nauki, jeżeli chcesz uczyć się innego zestawu kliknij   @Html.ActionLink("tutaj.", "List", "NaukaZestaw", null, new { @class = "AutoMoveLink" })</span>
}

NaukaFiszek/Views/Gra/Hangman.cshtml
@model DTO.Models.HangmanGameState
@{
    Layout = null;
}
<style>
    .CharResponse {
        border-style: solid;
        border-color: black;
        width: 100px;
        height: 100px;
        display: inline-block;
        font-size: 72px;
        text-align: center;
    }

    #hangMan {
        background: url("../Content/man.png");
        width: 75px;
        height: 200px;
    }
</style>
<img id="hangMan" src="~/Content/img_trans.gif" />
<div></div>
<div class="form-horizontal">
    <h4>Wisielec</h4>
    <hr />
    @Html.Partial("Prompt", Model.Fiche)
    <div class="form-group">

        @foreach (var item in Model.Fiche.Response)
        {
            <span class="CharResponse" data-hidechar=@item></span>
        }

    </div>
    <div class="form-group">

        @foreach (var item in DTO.Models.HangmanGameState.Alphabet)
        {
            <button class="buttonChar">@item</button>
        }
        <br />
        <span class="form-control">Lista prób :</span>
        <ol id="MissedList">
        </ol>
        <br />
        <label for="UserTryText">Twój strzał : </label>
        <input type="text" id="UserTryText" class="form-control" />
        <hr />
        <button id="CheckUserTryText" class="form-control">Sprawdź</button>
    </div>
</div>
@Html.Partial("Common")
<script src="~/Scripts/Game/Hangman.js"></script>

NaukaFiszek/Views/Gra/Prompt.cshtml
@model DTO.Models.Fiche
@{
    Layout = null;
    string urlFile = Url.Action("LoadFile", "Comon", new { id = Model.IdPromptFile });
}
<div class="form-group gameDiv" id="PromptGameDiv">
    <h3>Podpowiedź to:</h3>
    <h3>@Model.Prompt</h3>
    @if (Model.TypePrompt == DTO.Enums.ContentType.Sound)
    {
        <audio controls="controls">
            <source src=@urlFile />
        </audio>
    }
    @if (Model.TypePrompt == DTO.Enums.ContentType.Image)
    {
        <img src=@urlFile />
    }
    @if (Model.TypePrompt == DTO.Enums.ContentType.Movie)
    {
        <video controls="controls">
            <source src=@urlFile />
        </video>
    }
</div>

NaukaFiszek/Views/Gra/UserChose.cshtml
@model DTO.Models.GameState
@{
    Layout = null;
}
<h4>Określ czy wiesz</h4>
<hr />
@Html.Partial("Prompt", Model.Fiche)
@Html.Partial("Common")
<script src="~/Scripts/Game/UserChose.js"></script>

NaukaFiszek/Views/Gra/WriteText.cshtml
@model DTO.Models.GameState
@{
    Layout = null;
}
<div class="form-horizontal">
    <h4>Napisz odpowiedź</h4>
    <hr />
    @Html.Partial("~/Views/Gra/Prompt.cshtml", Model.Fiche)
    <div class="form-group">
        <div>

            <label for="AnswerText" class="control-label col-md-2">Twoja odpowiedź</label>
            <input type="text" id="AnswerText" class="form-control text-box single-line">

        </div>
    </div>
</div>
@Html.Partial("~/Views/Gra/Common.cshtml")
<script src="~/Scripts/Game/WriteText.js"></script>